platform :ios, '15.0'

project 'GatherLoopOC', {
  'Debug' => :debug,
  'Release' => :release,
}

target 'GatherLoopOC' do
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['TARGETED_DEVICE_FAMILY'] = '1'
      config.build_settings['SUPPORTED_PLATFORMS'] = 'iphoneos iphonesimulator'
      config.build_settings.delete('CODE_SIGN_IDENTITY[sdk=watchos*]')
      config.build_settings.delete('CODE_SIGN_IDENTITY[sdk=appletvos*]')
    end
  end
end
